name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Build LaTeX document
      run: |
        docker run --rm -v ${{ github.workspace }}:/data csmith/awesome-cv-builder xelatex -interaction=nonstopmode -halt-on-error delay_cv.tex

    - name: Upload built PDF
      uses: actions/upload-artifact@v2
      with:
        name: CV
        path: delay_cv.pdf
